image: docker:latest


stages:
  - build


build-prod:
  image: ruby:2.6
  stage: build
  script:
    - bundle install
    - bundle exec jekyll build -d public

  artifacts:
    paths:
      - public
    expire_in: 60min
  only:
    - master
